// src/app/zelda/editor/main-content.tsx
import * as React from 'react';
import {Tab, Tabs} from 'react-bootstrap';
import VisibleMapEditor from './containers/visible-map-editor';
import VisibleMapPreview from './containers/visible-map-preview';
import VisibleTilePalette from './containers/visible-tile-palette';
import {ZeldaGame} from '../ZeldaGame';
import {Map} from '../Map';
import CodeViewer from './code-viewer';
import EventTable from './event-editor';
import VisibleEnemySelector from './containers/visible-enemy-selector';

interface MainContentProps {
    game: ZeldaGame;
    currentScreenRow: number;
    currentScreenCol: number;
    currentScreenChanged: (game: ZeldaGame) => void;
}

interface MainContentState {
    loading: boolean;
    rowCount: number;
    colCount: number;
    selectedTileIndex: number; // TODO: This should be in IState
}

export default class MainContent extends React.Component<MainContentProps, MainContentState> {

    state: MainContentState = { rowCount: 0, colCount: 0, selectedTileIndex: -1, loading: true };

    componentDidMount() {

        const game: ZeldaGame = this.props.game;

        // This mimics what is loaded in LoadingState.
        // TODO: Share this code?
        game.assets.addImage('title', 'res/title.png');
        game.assets.addSpriteSheet('font', 'res/font.png', 9, 7, 0, 0);
        game.assets.addSpriteSheet('link', 'res/link.png', 16, 16, 1, 1, true);
        game.assets.addSpriteSheet('overworld', 'res/overworld.png', 16, 16);
        game.assets.addImage('hud', 'res/hudMockup.png');
        game.assets.addJson('overworldData', 'res/data/overworld.json');

        const that: MainContent = this;
        game.assets.onLoad(() => {

            //vm.game = game;
            game.map = new Map();
            game.map.fromJson(game.assets.get('overworldData'));
            this._setCurrentScreen(7, 6);

            that._installKeyHandlers();

            that.setState({ loading: false,
                rowCount: game.map.rowCount - 1, colCount: game.map.colCount - 1,
                selectedTileIndex: 1 });
        });
    }

    private _installKeyHandlers() {

        document.addEventListener('keydown', (e: KeyboardEvent) => {

            let row: number;
            let col: number;

            switch (e.which) {

                case 37:
                    console.log('left');
                    row = this.props.currentScreenRow;
                    col = this.props.currentScreenCol;
                    if (col > 0) {
                        this._setCurrentScreen(row, col - 1);
                    }
                    e.preventDefault();
                    break;

                case 38:
                    console.log('up');
                    row = this.props.currentScreenRow;
                    col = this.props.currentScreenCol;
                    if (row > 0) {
                        this._setCurrentScreen(row - 1, col);
                    }
                    e.preventDefault();
                    break;

                case 39:
                    console.log('right');
                    row = this.props.currentScreenRow;
                    col = this.props.currentScreenCol;
                    if (col < this.props.game.map.colCount - 1) {
                        this._setCurrentScreen(row, col + 1);
                    }
                    e.preventDefault();
                    break;

                case 40:
                    console.log('down');
                    row = this.props.currentScreenRow;
                    col = this.props.currentScreenCol;
                    if (row < this.props.game.map.rowCount - 1) {
                        this._setCurrentScreen(row + 1, col);
                    }
                    e.preventDefault();
                    break;

            }
        });
    }

    private _setCurrentScreen(row: number, col: number) {
        this.props.game.map.setCurrentScreen(row, col);
        this.props.currentScreenChanged(this.props.game);
    }

    render() {

        if (this.state.loading) {
            return (
                <span>Yo</span>
            );
        }

        const currentScreenRow: number = this.props.currentScreenRow;
        const currentScreenCol: number = this.props.currentScreenCol;

        return (

            <div className="container">

                <div className="row">

                    <div className="col-md-8">

                        <div className="panel panel-default">
                            <div className="panel-heading">
                                <h3 className="panel-title">
                                    Screen ({currentScreenRow}, {currentScreenCol}) / ({this.state.rowCount}, {this.state.colCount})
                                </h3>
                            </div>
                            <div className="panel-body">
                                <VisibleMapEditor/>
                            </div>
                        </div>

                        <div className="panel panel-default">
                            <div className="panel-heading">
                                <h3 className="panel-title">Map Preview</h3>
                            </div>
                            <div className="panel-body">
                                <VisibleMapPreview/>
                            </div>
                        </div>
                    </div>

                    <div className="col-md-4">

                        <Tabs id="tabSet1" defaultActiveKey={0} className="panel panel-default">
                            <Tab eventKey={0} title="Tile Palette">

                                <div className="panel panel-default">
                                <div className="panel-heading">
                                <h3 className="panel-title">Tile Palette</h3>
                                </div>
                                <div className="panel-body">
                                    <VisibleTilePalette/>
                                </div>
                                </div>

                            </Tab>

                            <Tab eventKey={1} title="Events">

                                <div className="panel-body">
                                    <EventTable game={this.props.game}
                                            events={this.props.game.map.currentScreen.events} />
                                </div>

                            </Tab>

                        </Tabs>

                        <div className="panel panel-default">
                            <div className="panel-heading">
                                <h3 className="panel-title">Enemies</h3>
                            </div>
                            <div className="panel-body">
                                <VisibleEnemySelector/>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="row">
                    <CodeViewer game={this.props.game} />
                </div>

            </div>
        );
    }
}

// src/editor/main-content.vue
<template>
    <v-container>

        <v-layout>
            <v-col class="xs8">
                <actionable-panel :title="title">
                    <map-editor :game="game" :selected-tile-index="selectedTileIndex"/>
                </actionable-panel>

                <actionable-panel title="Map Preview" v-if="game">
                    <map-preview :game="game" :map="game.map" :last-modified="$store.state.lastModified"/>
                </actionable-panel>
            </v-col>

            <v-col class="xs4" v-if="$store.state.currentScreen">

                <v-card class="control-group-bottom-margin tabbed-pane-styles" outlined>

                    <v-tabs v-model="selectedTab" bg-color="primary">

                        <v-tab class="editor-tab" value="tab-1">
                            Tile Palette
                        </v-tab>

                        <v-tab class="editor-tab" value="tab-2">
                            Events
                        </v-tab>

                        <v-tab class="editor-tab" value="tab-3">
                            Misc
                        </v-tab>
                    </v-tabs>

                    <v-tabs-window v-model="selectedTab">

                        <v-tabs-window-item key="tilePalette" value="tab-1">
                            <v-card flat outlined>
                                <v-card-text>
                                    <tile-palette :game="game" :tileset="game.map.tileset"
                                                  :selected-tile-index="selectedTileIndex"
                                                  @tileSelected="onTileSelected"/>
                                </v-card-text>
                            </v-card>
                        </v-tabs-window-item>

                        <v-tabs-window-item key="eventEditor" value="tab-2">
                            <v-card flat outlined>
                                <v-card-text style="padding: 0">
                                    <event-editor :game="game" v-model="$store.state.currentScreen.events"/>
                                </v-card-text>
                            </v-card>
                        </v-tabs-window-item>

                        <v-tabs-window-item key="screenMisc" value="tab-3">
                            <v-card flat outlined>
                                <v-card-text v-if="game">
                                    <screen-misc :screen="game.map.currentScreen"/>
                                </v-card-text>
                            </v-card>
                        </v-tabs-window-item>
                    </v-tabs-window>
                </v-card>

                <actionable-panel title="Enemies" :padded="false">
                    <enemy-selector :game="game" v-model="$store.state.currentScreen.enemyGroup"/>
                </actionable-panel>
            </v-col>
        </v-layout>

        <v-layout>
            <v-col class="xs12">

                <actionable-panel title="Map JSON">
                    <code-viewer :game="game"/>
                </actionable-panel>
            </v-col>
        </v-layout>
    </v-container>
</template>

<script lang="ts">
import MapEditor from '@/editor/map-editor.vue';
import { ZeldaGame } from '@/ZeldaGame';
import ScreenMisc from '@/editor/screen-misc.vue';
import TilePalette from '@/editor/tile-palette.vue';
import EventEditor from '@/editor/event-editor.vue';
import MapPreview from '@/editor/map-preview.vue';
import ActionablePanel from '@/editor/actionable-panel/actionable-panel.vue';
import CodeViewer from '@/editor/code-viewer.vue';
import EnemySelector from '@/editor/enemy-selector.vue';

export default {

    name: 'MainContent',
    components: {
        EnemySelector,
        ActionablePanel,
        CodeViewer,
        EventEditor,
        MapEditor,
        MapPreview,
        ScreenMisc,
        TilePalette,
    },

    data() {
        return {
            game: null, // ZeldaGame | null
            selectedTileIndex: 1,
            selectedTab: 'tab-1',
        };
    },

    computed: {
        title(): string {
            const curRow: number = this.$store.state.currentScreenRow;
            const curCol: number = this.$store.state.currentScreenCol;
            const rowCount: number = this.$store.state.game.map ? this.$store.state.game.map.rowCount - 1 : 0;
            const colCount: number = this.$store.state.game.map ? this.$store.state.game.map.colCount - 1 : 0;
            return `Screen (${curRow}, ${curCol}) / (${rowCount}, ${colCount})`;
        },
    },

    methods: {
        installKeyHandlers() {
            document.addEventListener('keydown', (e: KeyboardEvent) => {
                let row: number;
                let col: number;

                switch (e.which) {
                    case 37:
                        console.log('left');
                        row = this.$store.state.currentScreenRow;
                        col = this.$store.state.currentScreenCol;
                        if (col > 0) {
                            this.setCurrentScreen(row, col - 1);
                        }
                        e.preventDefault();
                        e.stopPropagation();
                        break;

                    case 38:
                        console.log('up');
                        row = this.$store.state.currentScreenRow;
                        col = this.$store.state.currentScreenCol;
                        if (row > 0) {
                            this.setCurrentScreen(row - 1, col);
                        }
                        e.preventDefault();
                        break;

                    case 39:
                        console.log('right');
                        row = this.$store.state.currentScreenRow;
                        col = this.$store.state.currentScreenCol;
                        if (col < this.game!.map.colCount - 1) {
                            this.setCurrentScreen(row, col + 1);
                        }
                        e.preventDefault();
                        break;

                    case 40:
                        console.log('down');
                        row = this.$store.state.currentScreenRow;
                        col = this.$store.state.currentScreenCol;
                        if (row < this.game!.map.rowCount - 1) {
                            this.setCurrentScreen(row + 1, col);
                        }
                        e.preventDefault();
                        break;
                }
            });
        },

        onTileSelected(index: number) {
            (console as any).log('selected tile in palette: ' + index);
            this.selectedTileIndex = index;
        },

        setCurrentScreen(row: number, col: number) {
            this.$store.commit('setCurrentScreen', { row, col });
            // this.currentScreenChanged();
        },
    },

    mounted() {
        const game: ZeldaGame = (window as any).game;

        // This mimics what is loaded in LoadingState.
        // TODO: Share this code?
        game.assets.addImage('title', '/res/title.png');
        game.assets.addSpriteSheet('font', '/res/font.png', 9, 7, 0, 0);
        game.assets.addSpriteSheet('link', 'res/link.png', 16, 16, 1, 1, true);
        game.assets.addSpriteSheet('overworld', 'res/overworld.png', 16, 16);
        game.assets.addSpriteSheet('labyrinths', 'res/level1.png', 16, 16);
        game.assets.addImage('hud', 'res/hud.png');
        game.assets.addJson('overworldData', 'res/data/overworld.json');
        game.assets.addJson('level1Data', 'res/data/level1.json');

        game.assets.onLoad(() => {
            this.$nextTick(() => {
                game.startNewGame();
                this.game = game;

                this.setCurrentScreen(7, 6);
            });

            this.installKeyHandlers();
        //
        // this.setState({ loading: false,
        //     rowCount: game.map.rowCount - 1, colCount: game.map.colCount - 1,
        //     selectedTileIndex: 1 });
        });
    },
}
</script>

<style lang="scss" scoped>
.elevation-1.tabbed-pane-styles {
    box-shadow: none !important;
}

.editor-tab {
    // TODO: Match this with that used in the tabbed pane in actionable-panel
    font-size: 1rem;
    /*letter-spacing: normal;*/
    text-transform: none;
}
</style>
