// src/editor/screen-misc.vue
<template>
    <div>
        <div>
            <label>Music</label>
            <v-select :items="songs" v-model="music" @change="onMusicChanged"/>
        </div>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';
import { Screen } from '@/Screen';
import { Watch } from 'vue-property-decorator';

@Component
export default class ScreenMisc extends Vue {

    private readonly songs: any[] = [
        { text: '(default)', value: null },
        { text: 'No music', value: 'none' },
        { text: 'Overworld', value: 'overworldMusic' },
        { text: 'Labyrinth', value: 'labyrinthMusic' }
    ];

    private music: string = this.songs[1].value;

    onMusicChanged(newValue: string) {
        this.$store.commit('setCurrentScreenMusic', newValue);
        console.log('New music: ' + newValue);
    }

    @Watch('screen')
    onScreenChanged(newScreen: Screen) {
        // "|| null" so we properly render for undefined
        this.music = newScreen ? newScreen.music || null : null;
    }

    get screen(): Screen {
        return this.$store.state.currentScreen;
    }
}
</script>

<style lang="less">

</style>

// src/app/zelda/editor/screen-misc.tsx
import * as React from 'react';
import Select, { SelectOnChangeEvent } from './select';
import { LabelValuePair } from './label-value-pair';
import { Screen } from '../Screen';

export interface ScreenMiscProps {
    screen: Screen | null;
}

interface ScreenMiscState {

}

export default class ScreenMisc extends React.Component<ScreenMiscProps, ScreenMiscState> {

    private songs: LabelValuePair<string>[];

    constructor(props: ScreenMiscProps) {

        super(props);

        this.songChanged = this.songChanged.bind(this);
    }

    componentWillMount() {

        this.songs = [
            { label: '(default)', value: null },
            { label: 'No music', value: 'none' },
            { label: 'Overworld', value: 'overworldMusic' },
            { label: 'Labyrinth', value: 'labyrinthMusic' }
        ];
    }

    songChanged(e: SelectOnChangeEvent<string>) {
        this.props.screen!.music = e.newValue;
    }

    render() {
        return (
            <div>
                <div className="form-group">
                    <label>Music</label>
                    <Select choices={this.songs}
                            initialValue={this.props.screen!.music}
                            onChange={this.songChanged}/>
                </div>
            </div>
        );
    }
}
